// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using question_api;

#nullable disable

namespace question_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("question_api.Model.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuestoesAnonimas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc6afd20-75d1-4a07-9cf8-4c817b9955ad"),
                            CorrectAnswer = 1,
                            Option1 = "Garbage Collector",
                            Option2 = "Memory Allocator",
                            Option3 = "Memory Manager",
                            Option4 = "Heap Manager",
                            Option5 = "Stack Manager",
                            Prompt = "Qual das seguintes opções é usada para gerenciar a memória no .NET?"
                        },
                        new
                        {
                            Id = new Guid("4f2a1272-a40e-4b8d-9db3-523d2c92485c"),
                            CorrectAnswer = 1,
                            Option1 = "Object",
                            Option2 = "Base",
                            Option3 = "Core",
                            Option4 = "System",
                            Option5 = "Root",
                            Prompt = "Qual é a classe base para todas as classes no .NET?"
                        },
                        new
                        {
                            Id = new Guid("704c4a7b-0c0d-4cc0-bbe7-3ad0aead54a7"),
                            CorrectAnswer = 2,
                            Option1 = "null",
                            Option2 = "void",
                            Option3 = "empty",
                            Option4 = "none",
                            Option5 = "nil",
                            Prompt = "Qual palavra-chave é usada para definir um método que não retorna valor?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
